version: '3'
services:
    guacamole:
        image: abesnier/guacamole
        restart: always
        container_name: guacamole_noerr
        environment:
            - TZ=America/New_York
        volumes:
            - "guac_data:/config"
        ports:
            - "9800:8080"
